# Generated by Django 3.2.9 on 2021-12-29 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowshowchart',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowshowchart',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.standard'),
        ),
        migrations.AddField(
            model_name='course',
            name='prep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.prep'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='know_show_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.knowshowchart'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.question'),
        ),
    ]
