# Generated by Django 3.2.9 on 2021-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowshowchart',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
