# Generated by Django 3.2.9 on 2021-12-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_knowshowchart_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
